config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root to: 'pages#home'
  
  devise_for :users, path: '', path_names:{sign_in:'login', sign_out:'logout', sign_up:'', registration:'register', confirmation:'confirmation'}, controllers: {confirmations: 'users/confirmations'}
              
                      
  devise_scope :user do
    get '/profil', to: 'devise/registrations#edit', as: :profil
  end

  # Operations
  resources :operations

end

app/views/pages/home.html.erb
<div class="md:flex md:flex-row sm:flex-column md:py-5">
  <div class="shadow-sm border border-transparent rounded-md py-3 md:basis-1/3 flex flex-row bg-sky-100 md:mr-5 mb-4">
    <span class="ml-2 font-semibold text-lg basis-2/4">
      Total Entrée : 
    </span>
    <span class="font-light text-2xl basis-2/4">
      <%= @total_incomes %> XOF
    </span> 
  </div>

  <div class="shadow-sm border border-transparent rounded-md py-3 md:basis-1/3 flex flex-row bg-red-100 md:mx-5 mb-4">
    <span class="ml-2 font-semibold text-lg basis-2/4">
      Total dépense : 
    </span> 
    <span class="font-light text-2xl basis-2/4">
      <%= @total_expenses %> XOF
    </span> 
  </div>

  <div class="shadow-sm border border-transparent rounded-md py-3 md:basis-1/3 flex flex-row bg-violet-100 md:ml-5 mb-4">
    <span class="ml-2 font-semibold text-lg basis-2/4">
      Reste : 
    </span>
    <span class="font-light text-2xl basis-2/4">
      <%= @rest %> XOF
    </span> 
  </div>
</div>

<hr class="py-5">

<div class="sm:flex mb-7 space-y-4">
  <h3 class="font-bold text-2xl sm:flex-auto sm:w-64"> 5 Dernières opérations </h3>
  <div>
    <a class="px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-sky-400 hover:bg-sky-500" href="<%= operations_path %>">Toutes les opération</a>
  </div>
</div>

<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-100 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-100">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date & Heure</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type d'opération</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Montant (en XOF)</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Motif</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% if @operations.count > 0 %>
              <% @operations.each do |operation| %>
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= operation.datetime.strftime("%d %B %Y à %Hh%M") %></td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <% if operation.operation_type == 1 %>
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"> Entrée </span>
                      <% else %>
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800"> Dépense </span>
                      <% end %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= operation.amount %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= truncate(operation.motif, :length => 55) %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <a href="<%= operation_path(operation.id) %>" class="text-sky-500 hover:text-sky-700">Détails</a>
                    </td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                  <td colspan="5" class="px-6 py-4 whitespace-nowrap text-center text-gray-400"> Aucune opération </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="my-14 text-center">
  <a class="px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-sky-600 hover:bg-sky-700" href="<%= new_operation_path %>">Nouvelle opération</a>
</div>