config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root to: 'pages#home'
  
  devise_for :users, path: '', path_names:{sign_in:'login', sign_out:'logout', sign_up:'', registration:'register', confirmation:'confirmation'}, controllers: {confirmations: 'users/confirmations'}
              
                      
  devise_scope :user do
    get '/profil', to: 'devise/registrations#edit', as: :profil
  end

  # Operations
  resources :operations

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark bg-gray-50">
  <head>
    <title>TestEverPartners</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
      <div>
        <nav class="bg-white fixed w-full z-10 top-0" data-controller="navbar">
          <div class="max-w-7xl mx-auto px-4 sm:px-6">
            <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
              <div class="flex justify-start lg:w-0 lg:flex-1">
                <a href="<%= root_path %>">
                  <img class="h-8 w-auto sm:h-10" src="https://ever.partners/wp-content/themes/landing-page-everpartners-1/images/logo.png" alt="">
                </a>
              </div>
              
              
              <div class="-mr-2 -my-2 md:hidden">
                <button type="button" data-action="click->navbar#mobile" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
                  <span class="sr-only">Open menu</span>
                  <!-- Heroicon name: outline/menu -->
                  <svg class="h-6 w-6" data-navbar-target="stateClose" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>

                  <svg class="hidden h-6 w-6" data-navbar-target="stateOpen" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>

              <nav class="hidden md:flex space-x-10">
                <% if user_signed_in? %>
                  <%= link_to "Espace Principal", root_path, class: "#{'text-sky-600' if current_page?(root_path)} text-base font-medium text-gray-500 hover:text-sky-400" %>
                  <%= link_to "Opérations", operations_path, class: "#{'text-sky-600' if current_page?(operations_path)} text-base font-medium text-gray-500 hover:text-sky-400" %>
                  <%= link_to "Profil", profil_path, class: "#{'text-sky-600' if current_page?(profil_path)} text-base font-medium text-gray-500 hover:text-sky-400" %>
                <% else %>
                <% end %>
              </nav>
              <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
                <% if user_signed_in? %>     
                  <%= link_to "Déconnexion", destroy_user_session_path, data: {method: :delete, confirm: "Êtes vous vous sûr de vouloir vous déconnecter?"}, class: "px-4 py-1 border border-transparent rounded-md text-base font-medium text-gray-500 hover:text-sky-400" %>
                <% else %>
                  <%= link_to "Connexion", new_user_session_path, class: "whitespace-nowrap text-base font-medium text-gray-500 hover:text-sky-400" %>
                  <%= link_to "Inscription", new_user_registration_path, class: "ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-sky-400 hover:bg-sky-500" %>
                <% end %>
              </div>
            </div>
            
            <div class="hidden" data-navbar-target="show" id="mobile-menu">
              <div class="px-2 pt-2 pb-3 space-y-1">
                <% if user_signed_in? %>
                  <%= link_to "Espace Principal", root_path, class: "#{'text-gray-600' if current_page?(root_path)} text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                  <%= link_to "Opérations", operations_path, class: "#{'text-gray-600' if current_page?(operations_path)} text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                  <%= link_to "Profil", profil_path, class: "#{'text-gray-600' if current_page?(profil_path)} text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                  <%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                <% else %>
                  <%= link_to "Connexion", new_user_session_path, class: "#{'text-gray-600' if current_page?(new_user_session_path)} text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                  <%= link_to "Inscription", new_user_registration_path, class: "#{'text-gray-600' if current_page?(new_user_registration_path)} text-gray-400 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                <% end %>

              </div>
            </div> 

          </div>
        </nav>

        <div class="mt-20 md:mt-24">
          <% if flash[:notice] %>
            <div class="bg-green-100 mb-2 p-3 text-green-800 mx-5 mt-3">
              <%= flash[:notice] %>
            </div>
          <% end %>

          <% if flash[:alert] %>
            <div class="bg-red-100 mb-2 p-3 text-red-800 mx-5 mt-3">
              <%= flash[:alert] %>
            </div>
          <% end %>

          <main class="container mx-auto py-6 mt-4">
            <%= yield %>
          </main>
          
        </div>
      </div>

  </body>
</html>