config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root to: 'pages#home'
  
  devise_for :users, path: '', path_names:{sign_in:'login', sign_out:'logout', sign_up:'', registration:'register', confirmation:'confirmation'}, controllers: {confirmations: 'users/confirmations'}
              
                      
  devise_scope :user do
    get '/profil', to: 'devise/registrations#edit', as: :profil
  end

  # Operations
  resources :operations

end

app/models/operation.rb
class Operation < ApplicationRecord

    belongs_to :user

    validates :amount, :motif, :operation_type, :datetime, presence: true
    validates :amount, numericality: true
    validates :user, presence: true
    
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController

  before_action :set_operation, only: [:edit, :update, :show, :destroy]
  def index
    @operations = Operation.where("user_id" => current_user.id).order(datetime: :desc)
  end

  def new
    @operation = Operation.new
  end

  def create
    @operation = Operation.new(operation_params)
    @operation.user= current_user
    if @operation.valid?
      @operation.save
      redirect_to root_path, success: 'Opération ajoutée avec succès.'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @operation.update(operation_params)
      redirect_to operations_path, success: "Opération modifiée avec succès"
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
      if @operation.destroy
        redirect_to operations_path, success: "Opération supprimée avec succès"
      end
  end

  private

  def operation_params
    params.require(:operation).permit(:amount, :motif, :operation_type, :datetime)
  end
	
  def set_operation
    @operation = Operation.find(params["id"])
  end
end

app/views/operations/edit.html.erb
<div class="mx-auto md:w-2/5 bg-white border border-b rounded-xl p-4">
    <div class="w-full align-items-center">
        <div class="space-y-5">
            <div class="text-2xl font-bold"> Editer opération </div><hr>
            <div class="mr-5">
                <%= form_for @operation do |f| %>
                    <div class="row mb-3">
                        <%= f.label :amount, "Montant", class: 'text-xs' %>
                        <div class="">
                            <%= f.text_field :amount, class: 'rounded-lg w-full h-9' %>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <%= f.label :motif, "Motif", class: 'text-xs' %>
                        <div class="">
                            <%= f.text_field :motif, class: 'rounded-lg w-full h-9' %>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <%= f.label :operation_type, "Type d'opération", class: 'text-xs' %>
                        <div class="">
                            <%= f.select :operation_type, {'Dépense'=>0,'Entrée'=>1}, {}, class: "rounded-lg w-full h-9" %>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <%= f.label :datatime, "Date & Heure", class: 'text-xs' %>
                        <div class="">
                            <%= f.datetime_field :datetime, class: 'rounded-lg w-full h-9' %>
                        </div>
                    </div>

                    <div class="">
                        <button type="submit" class="bg-sky-400 text-white hover:bg-sky-600 px-4 py-2 rounded-md text-sm">Mettre à jour</button>
                    </div>
                    
                <% end %>
            </div>
        </div>
        <p class="text-sm mt-5">Retourner vers  <%= link_to "les détails de l'opération", operation_path, class: "text-sky-500 hover:text-sky-700" %></p>
    </div>
</div>

app/views/operations/index.html.erb
<div class="sm:flex mb-7 space-y-4">
    <h3 class="font-bold text-2xl sm:flex-auto sm:w-64"> Toutes vos opérations </h3>
    <div>
        <a class="px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-sky-400 hover:bg-sky-500" href="<%= new_operation_path %>">Nouvelle opération</a>
    </div>
</div>

<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-100">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date & Heure</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type d'opération</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Montant (en XOF)</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Motif</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% if @operations.count > 0 %>
                <% @operations.each do |operation| %>
                    <tr>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= operation.datetime.strftime("%d %B %Y à %Hh%M") %></td>
                        <td class="px-6 py-4 whitespace-nowrap">
                          <% if operation.operation_type == 1 %>
                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"> Entrée </span>
                          <% else %>
                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800"> Dépense </span>
                          <% end %>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= operation.amount %></td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= truncate(operation.motif, :length => 55) %></td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <a href="<%= operation_path(operation.id) %>" class="text-sky-500 hover:text-sky-700">Détails</a>
                        </td>
                    </tr>
                <% end %>
            <% else %>
                <tr>
                    <td colspan="5" class="px-6 py-4 whitespace-nowrap text-center text-gray-400"> Aucune opération </td>
                </tr>
            <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/operations/new.html.erb
<% if @operation.errors.any? %>
    <div class="bg-red-100 mb-2 p-3 text-red-800">
        <p>Vous avez <span class="font-bold"><%= @operation.errors.count %></span> erreur(s) :</p>
        <ul class="list-disc list-inside pl-4">
            <% @operation.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="mx-auto md:w-2/5 bg-white border border-b rounded-xl p-4">
    <div class="w-full align-items-center">
        <div class="space-y-5">
            <div class="text-2xl font-bold"> Nouvelle opération </div><hr>
            <div class="mr-5">
                <%= form_for @operation do |f| %>
                    <div class="row mb-3">
                        <%= f.label :amount, "Montant", class: 'text-xs' %>
                        <div class="">
                            <%= f.text_field :amount, class: 'rounded-lg w-full h-9' %>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <%= f.label :motif, "Motif", class: 'text-xs' %>
                        <div class="">
                            <%= f.text_field :motif, class: 'rounded-lg w-full h-9' %>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <%= f.label :operation_type, "Type d'opération", class: 'text-xs' %>
                        <div class="">
                            <%= f.select :operation_type, {'Dépense'=>0,'Entrée'=>1}, {}, class: "rounded-lg w-full h-9" %>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <%= f.label :datatime, "Date & Heure", class: 'text-xs' %>
                        <div class="">
                            <%= f.datetime_field :datetime, class: 'rounded-lg w-full h-9' %>
                        </div>
                    </div>

                    <div class="">
                        <button type="submit" class="bg-sky-400 text-white hover:bg-sky-600 px-4 py-2 rounded-md text-sm">Créer</button>
                    </div>
                    
                <% end %>
            </div>
        </div>
        <p class="text-sm mt-5">Retourner vers toutes <%= link_to "les opérations", operations_path, class: "text-sky-500 hover:text-sky-700" %></p>
    </div>
</div>

app/views/operations/show.html.erb
<div class="bg-white shadow-sm overflow-hidden sm:rounded-lg mx-auto mb-5">
  <div class="px-4 py-5 sm:px-6 grid grid-cols-2 content-between">
    <h3 class="text-lg leading-6 font-medium text-gray-900">Détails Opération</h3>
    <div class="grid justify-items-end">
        <div class="flex flex-column space-x-4">
            <%= link_to "Editer", edit_operation_path, class: "px-2 bg-sky-500 hover:bg-sky-600 text-white rounded-full"%>
            <%= link_to "Supprimer", operation_path, data: {method: :delete, confirm: "Êtes-vous sûr de vouloir supprimer cette opération?"}, 
                class: "px-2 bg-red-500 hover:bg-red-600 text-white rounded-full" %>
        </div>
    </div>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Date & Heure</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @operation.datetime.strftime("%d %B %Y à %Hh%M") %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Montant</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @operation.amount %> CFA</dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Motif</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @operation.motif %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Type d'opération</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
            <% if @operation.operation_type == 1 %>
              <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"> Entrée </span>
            <% else %>
              <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800"> Dépense </span>
            <% end %>
        </dd>
      </div>
    </dl>
  </div>
</div>

<p class="text-right">Retourner vers <%= link_to "les opérations", operations_path, class: "text-sky-500 hover:text-sky-700" %></p>